{% set version = "3.0.5" %}
# Version bump reminder: Must manually check the file constraints to ensure 
# they match those similar to
# 2024/01 hmaarrfk -- However we have found that these get somewhat stale
# https://keras.io/getting_started/#compatibility-matrix

package:
  name: keras
  version: {{ version }}

source:
  url: https://github.com/keras-team/keras/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0e23205f2d8f434ded17ca9efb116cdb7b6d19736e576456c28aea685a7f195f

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    # see https://github.com/keras-team/keras/blob/master/oss_setup.py
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - absl-py
    - numpy
    - rich
    - namex
    - h5py
    - dm-tree
    - ml-dtypes
  run_constrained:
    - tensorflow >=2.15.0,<2.17.0a
    - jax 0.4
    - torch 2.1

test:
  requires:
    - pip
  commands:
    - pip check
    # even the numpy backend requires jax....
    # https://github.com/keras-team/keras/issues/18840
    # - KERAS_BACKEND=numpy python -c "import keras"

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - ngam
    - mariusvniekerk
    - croth1
    - ocefpaf
    - xhochy
    - hmaarrfk
