{% set version = "3.0.0" %}
# Must manually check the file
# https://github.com/keras-team/keras/blob/v{{ version }}/requirements-tensorflow-cuda.txt
{% set tf_major_minor = "2.16" %}

package:
  name: keras
  version: {{ version }}

source:
  url: https://github.com/keras-team/keras/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f7de0fdc2000ee3f98119b382b4068548cf260fa145728b16306fc2c7cb9015c

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    # see https://github.com/keras-team/keras/blob/master/oss_setup.py
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - absl-py
    - numpy
    - rich
    - namex
    - h5py
    - dm-tree
  run_constrained:
    - tensorflow {{ tf_major_minor }}

test:
  requires:
    - pip
  commands:
    - pip check
    # even the numpy backend requires jax....
    # https://github.com/keras-team/keras/issues/18840
    # - KERAS_BACKEND=numpy python -c "import keras"

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - ngam
    - mariusvniekerk
    - croth1
    - ocefpaf
    - xhochy
    - hmaarrfk
