{% set version = "2.11.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: keras
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py2.py3/k/keras/keras-{{ version }}-py2.py3-none-any.whl
    sha256: 38c6fff0ea9a8b06a2717736565c92a73c8cd9b1c239e7125ccb188b7848f65e
  - url: https://raw.githubusercontent.com/keras-team/keras/v{{ version }}/LICENSE
    sha256: 58d1e17ffe5109a7ae296caafcadfdbe6a7d176f0bc4ab01e12a689b0499d8bd

build:
  script: {{ PYTHON }} -m pip install -vv keras-{{ version }}-py2.py3-none-any.whl
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
  run_constrained:
    - tensorflow {{ major_minor }}.*

test:
  requires:
    - pip
  commands:
    - pip check
  # Cyclic dependency with tensorflow
  # imports:
  #  - keras

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - mariusvniekerk
    - croth1
    - ocefpaf
    - xhochy
    - hmaarrfk
