{% set version = "2.4.3" %}

package:
  name: keras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/K/Keras/Keras-{{ version }}.tar.gz
  sha256: fedd729b52572fb108a98e3d97e1bac10a81d3917d2103cc20ab2a5f03beb973

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.9.1
    - scipy >=0.14
    - pyyaml
    - h5py
    - tensorflow >=2.2

test:
  imports:
    - keras
    - keras.backend
    - keras.datasets
    - keras.engine
    - keras.layers
    - keras.preprocessing
    - keras.utils
    - keras.wrappers

about:
  home: https://github.com/keras-team/keras
  license: MIT
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - mariusvniekerk
    - croth1
    - ocefpaf
