{% set version = "2.14.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: keras
  version: {{ version }}

source:
  - url: https://pypi.io/packages/py3/k/keras/keras-{{ version }}-py3-none-any.whl
    sha256: d7429d1d2131cc7eb1f2ea2ec330227c7d9d38dab3dfdf2e78defee4ecc43fcd
  - url: https://raw.githubusercontent.com/keras-team/keras/v{{ version }}/LICENSE
    sha256: 58d1e17ffe5109a7ae296caafcadfdbe6a7d176f0bc4ab01e12a689b0499d8bd

build:
  script: {{ PYTHON }} -m pip install -vv keras-{{ version }}-py3-none-any.whl
  noarch: python
  number: 0

requirements:
  host:
    # see https://github.com/keras-team/keras/blob/master/oss_setup.py
    - python >=3.8
    - pip
  run:
    - python >=3.8
  run_constrained:
    - tensorflow {{ major_minor }}.*

test:
  requires:
    - pip
  commands:
    - pip check
  # Cyclic dependency with tensorflow
  # imports:
  #  - keras

about:
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning for Python

extra:
  recipe-maintainers:
    - ngam
    - mariusvniekerk
    - croth1
    - ocefpaf
    - xhochy
    - hmaarrfk
